pool:
  vmImage: vs2017-win2016

steps:
- powershell: |
    Get-PSDrive | Format-Table
    Get-WmiObject Win32_ComputerSystem
    Get-WmiObject Win32_processor
    Get-Process | Format-Table
    Get-ItemProperty HKLM:\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\* | Select-Object DisplayName, DisplayVersion, Publisher, InstallDate | Format-Table –AutoSize
    Invoke-RestMethod -Method Get -Uri http://myexternalip.com/raw
